# Generated by Django 3.1.7 on 2021-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='air_conditioners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('screen_type', models.CharField(max_length=10)),
                ('screen_size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='wm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=15)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
